# -*- coding: utf-8 -*-
"""Copy of numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQQ7zeDv8xluOnOcD3c8qjdsV4TodRkN
"""

import numpy as np
arr=np.array([[3,2,1],[2,4,6]])
print("array[2]:",arr)



import numpy as np
a=np.array([[2,3,4],[2,7,9]])
print("Unique element is:",np.unique(a))

import numpy as np
a=np.array([[1,4,6],[3,6,8]])
b=np.array([[4,7,8],[3,8,5]])
print("adding one to the element:",a+1)
print("subtract two from:",b-2)
print("sum of 1st array:",a.sum())
print("Sum of both array:",a.sum()+b.sum())

import numpy as np
a=np.array([[20,50,1],[60,1,90]])
print("maximum elements of column:",a.max(axis=0))